apiVersion: v1
kind: Service
metadata:
  name: logstash
  namespace: default
spec:
  selector:
    name: logstash
  ports:
    - name: main
      port: 5044
      targetPort: 5044
    - name: admin
      port: 25826
      targetPort: 25826
