apiVersion: v1
kind: Service
metadata:
  name: opensearch
  namespace: default
spec:
  selector:
    app: opensearch
  ports:
    - name: osn1
      port: 9200
      targetPort: 9200
    - name: osn2
      port: 9600
      targetPort: 9600